server:
  port: 8888

spring:
  application:
    name: config-repository
  security:
    user:
      name: @app.config-repository.username@
      password: @app.config-repository.password@
  cloud:
    config:
      server:
        git:
          uri: file:///@basedir@/../config-repos
  devtools:
    livereload:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: @app.discovery-service.url@
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
