server:
  port: 8888

spring:
  application:
    name: config-repository
  cloud:
    config:
      server:
        git:
          uri: file:///@basedir@/../config-repos
    loadbalancer:
      ribbon:
        enabled: false
  devtools:
    livereload:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
