spring:
  security:
    oauth2:
      client:
        registration:
          api-gateway:
            provider: keycloak
            client-id: api-gateway
            client-secret: bd8ea22a-4629-4d1a-8da9-789cb4948416
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # enable load balancer protocol lb://
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movie-service/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review-service/**
          filters:
            - StripPrefix=1
            - TokenRelay=
