server:
  port: 8084
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: secret
    key-store-type: pkcs12
    key-alias: dtxmaker
    key-password: secret

spring:
  security:
    oauth2:
      client:
        registration:
          api-gateway:
            provider: keycloak
            client-id: api-gateway
            client-secret: bd8ea22a-4629-4d1a-8da9-789cb4948416
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # enable load balancer protocol lb://
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movie-service/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review-service/**
          filters:
            - StripPrefix=1
            - TokenRelay=

eureka:
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    status-page-url: https://${eureka.hostname}:${server.port}/actuator/info
    health-check-url: https://${eureka.hostname}:${server.port}/actuator/health
    home-page-url: https://${eureka.hostname}:${server.port}/
