spring:
  jpa:
    open-in-view: false
  devtools:
    livereload:
      enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/microservices
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservices
  boot:
    admin:
      client:
        url: http://localhost:8002/admin
        username: "admin"
        password: "admin"

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
