server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: secret
    key-store-type: pkcs12
    key-alias: dtxmaker
    trust-store: classpath:truststore.p12
    trust-store-password: secret
    trust-store-type: pkcs12
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  security:
    oauth2:
      client:
        registration:
          cinema-app:
            provider: keycloak
            client-id: cinema-app
            client-secret: 75634444-167a-47d8-8f43-1c44f74cc43e
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    non-secure-port-enabled: false
    secure-port-enabled: true
    status-page-url: https://${eureka.hostname}:${server.port}/actuator/info
    health-check-url: https://${eureka.hostname}:${server.port}/actuator/health
    home-page-url: https://${eureka.hostname}:${server.port}/
