server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:h2:mem://./movies
    username: sa
  security:
    oauth2:
      client:
        registration:
          movie-service:
            provider: keycloak
            client-id: movie-service
            client-secret: LPSl717dDPv0MZbhnnCnQp1VwfCFR4ii
            authorization-grant-type: client_credentials
