server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:h2:mem://./reviews
    username: sa
  security:
    oauth2:
      client:
        registration:
          review-service:
            provider: keycloak
            client-id: review-service
            client-secret: P1cJ1f1Q22AWyOsoHt6kCjBJI30tFBDu
            authorization-grant-type: client_credentials
