server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:h2:mem://./reviews
    username: sa
  security:
    oauth2:
      client:
        registration:
          review-service:
            provider: keycloak
            client-id: review-service
            client-secret: abb0f2a1-a32a-4c59-8ecb-46784a83e7f2
            authorization-grant-type: client_credentials
