server:
  port: 8761

spring:
  application:
    name: discovery-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  devtools:
    livereload:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    prefer-ip-address: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka

management:
  endpoint:
    health:
      show-details: always
