server:
  port: 8761

spring:
  application:
    name: discovery-service
  security:
    user:
      name: @app.discovery-service.username@
      password: @app.discovery-service.password@
  boot:
    admin:
      client:
        url: @app.spring-boot-admin.url@
        username: @app.spring-boot-admin.username@
        password: @app.spring-boot-admin.password@
  devtools:
    livereload:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    prefer-ip-address: true
    service-url:
      defaultZone: @app.discovery-service.url@

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
