spring:
  application:
    name: movie-service
  config:
    import: configserver:config-repository
  cloud:
    config:
      username: @app.config-repository.username@
      password: @app.config-repository.password@
      discovery:
        enabled: true
        service-id: config-repository
      name: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: @app.discovery-service.url@
