server:
  port: 8002
  servlet:
    context-path: /admin

spring:
  application:
    name: spring-boot-admin-server
  security:
    user:
      name: "admin"
      password: "admin"
  boot:
    admin:
      client:
        url: http://localhost:${server.port}${server.servlet.context-path}
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    registry-fetch-interval-seconds: 5

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
